name: denwee
description: "Denwee mobile application"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# App version + build
version: 1.0.2+51

# Env
environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:

  # Flutter
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_crashlytics: ^5.0.4
  firebase_analytics: ^12.0.4

  # Intl
  intl: ^0.20.2

  # Localizations
  easy_localization: ^3.0.8

  # State managment
  flutter_bloc: ^9.1.1

  # Database
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40

  # Permissions
  permission_handler: ^12.0.1

  # Deeplinks
  app_links: ^6.4.1

  # Connectivity
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  # internet_connection_checker_plus: ^2.9.1

  # Ad's
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1
  gma_mediation_unity: ^1.6.2
  # gma_mediation_ironsource: ^2.1.0

  # Functional programming
  dartz: ^0.10.1

  # File manager
  path_provider: ^2.1.5

  # Dependencies
  json_annotation: ^4.9.0
  get_it: ^9.0.5
  injectable: ^2.6.0
  freezed_annotation: ^3.1.0

  # Local Database
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Device/Package info
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0

  # Misc
  app_settings: ^6.1.1

  # Animations & UI
  formz: ^0.8.0
  flutter_svg: ^2.1.0
  heroine: ^0.5.0+2
  timeago: ^3.7.1
  lottie: ^3.3.2
  animated_switcher_plus: ^1.4.0
  simple_animations: ^5.2.0
  circular_reveal_animation: ^2.0.2
  top_snackbar_flutter: ^3.3.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.3
  floating_bubbles: ^2.6.2
  animated_flip_counter: ^0.3.4
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1
  shimmer_animation: ^2.2.2
  flutter_sticky_header: ^0.8.0
  snap_scroll_physics: ^0.0.1+3
  animate_do: ^4.2.0
  email_validator: ^3.0.0
  flutter_inappwebview: ^6.1.5

  # Utils
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  utils:
    path: packages/utils/
  markdown_widget:
    path: packages/markdown_widget/

dev_dependencies:
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.1
  build_runner: ^2.10.3
  freezed: ^3.2.3
  analyzer: ^8.4.1
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/animations/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
